phaazon/hop.nvim

lua/hop/hint.lua, lua/hop/init.lua, lua/hop/perm.lua
This PR implements consecutive opts lookup: *local command options* > *global set options* > *default options*
For example, in this case
```lua
require('hop').setup({winblend = 60, teasing = false})
vim.api.nvim_set_keymap('n', '<leader>w', "<cmd>lua require'hop'.hint_words({teasing = true})<cr>", {})
```
`hint_words` action will be executed with the following `opts`:
```lua
opts = {
keys                 = 'asdghklqwertyuiopzxcvbnmfj', -- default
reverse_distribution = false,                        -- default
term_seq_bias        = 3 / 4,                        -- default
winblend             = 60,                           -- global
teasing              = true,                         -- local
}
```
This fixes the following issues:
- Not being able to set separate per-command options …
=> Make setting opts more versatile

lua/hop/hint.lua, lua/hop/init.lua
Fixes following madness:
Searching for `.` in `hint_char1(…)`
*before*
*after*
=> Escape special characters in char searches

doc/hop.txt, lua/hop/highlight.lua, lua/hop/init.lua, plugin/hop.vim
Some colorscheme uses hi clear before setting highlights as a standard way.
That leads to hop.nvim's highlights cleared.
This PR prevents the problem by using autocmd ColorScheme that triggered after loading a new color scheme.
fix #35
=> Reset highlighting after loading a new color scheme. #35

lua/hop/init.lua
Using the non-recursive version in case the user has `m` remapped.
Fixes #49
=> Use noremap normal command to avoid collision with user keymaps.

lua/hop/init.lua
People tend to cancel user input by interrupting it via `<c-c>`. Handle that case and clean up properly.
=> Handle interupted input

lua/hop/highlight.lua
Wanted to add some default support for `notermguicolors` users like me.  :) This adds `ctermfg` and `cterm` options to the default highlights.
=> Add default colors for cterm

lua/hop/hint.lua
If some unicode / multi-byte is present at column `col` on a given line
and that `wrap` is set, then after `col`, some hints will be truncated.
This was implemented in the first place to hint _only_ what’s visible
(so that we don’t waste time hinting stuff the user cannot even see). In
the case of `wrap` mode, the computation of what’s visible was buggy.
This commit patches this situation by converting the width into a byte
width, allowing to take into unicode and more specifically, multi-byte
fucking characters. Should work with emojis, too.
Relates to #72.
Test with emojis, because why not lol.
=> Fix truncated hints after unicode in wrap mode.

doc/hop.txt, lua/hop/hint.lua, lua/hop/init.lua, plugin/hop.vim
This first commit allows to apply the hints to only the previous part of
the cursor or what comes after.
This commit doesn’t currently check the column, only the line. The next
commit will add support for before / after on the current line and
should also add support for a way to reduce apply hints only to the
current line.
This is an alternative implementation of #59.
Relates to #71, #91.
=> Add HintDirection and read it from opts.

lua/hop/init.lua
calling like this `require('hop').setup()` instead of this `require('hop').setup{}` currently errors
=> don't error on empty invocation of setup

lua/hop/init.lua
Fixes https://github.com/phaazon/hop.nvim/issues/92#issuecomment-864527938
Also, improves #83, because calling `setup` without `{}` still throws an error, since `opts == nil`.
=> Fix default `create_hl_autocmd` value not being utilized

lua/hop/init.lua
See <https://github.com/neovim/neovim/issues/14236> for further details.
=> Switch off hack to mitigate neovim extmark bug.

doc/hop.txt, lua/hop/defaults.lua, lua/hop/init.lua
The first commit makes it so that when hopping, typing a special key like `<C-Space>` or `<Left>` will quit hopping. Previously hop would eat the key and do nothing with it.
The second commit adds a quit_key config option. The effect of this is that pressing the quit_key when hopping will quit hop without feeding the key through to neovim.
For example, I have `<C-Space>` mapped to `<Esc>` in visual mode. When hopping in visual mode, I want to be able to use `<C-Space>` to quit hopping without feeding that through which would also exit visual mode. This commit allows for that.
=> Make special keys quit hop and add a quit_key config option

doc/hop.txt
Noticed it was broken in https://github.com/NixOS/nixpkgs/pull/128723
```
Building help tags
Error detected while processing command line:
E154: Duplicate tag ":HopLine" in file /nix/store/0k7yc0wk7s6w8y3d46lr3vbksq2nlnpy-vimplugin-hop-nvim-2021-06-27/share/vim-plugins/hop-nvim/doc/hop.txt
E154: Duplicate tag ":HopLineAC" in file /nix/store/0k7yc0wk7s6w8y3d46lr3vbksq2nlnpy-vimplugin-hop-nvim-2021-06-27/share/vim-plugins/hop-nvim/doc/hop.txt
E154: Duplicate tag ":HopLineBC" in file /nix/store/0k7yc0wk7s6w8y3d46lr3vbksq2nlnpy-vimplugin-hop-nvim-2021-06-27/share/vim-plugins/hop-nvim/doc/hop.txtFailed to build help tags!
```
=> Fix doc tags

doc/hop.txt, lua/hop/init.lua
Well, this was even easier than the linestart thing :)
With this PR, my mapping now smoothly works with the following oneliner in my `.vimrc`:
```vimscript
nnoremap tD :lua require'hop'.hint_patterns({}, '\\d')<cr>
```
=> User can specify pattern to not be prompted with `hint_patterns`.

doc/hop.txt, lua/hop/hint.lua
By using `\k`, which depends on the `iskeyword` value, `hop.hint_word` behaviour's becomes consistent with all the native words' commands, like `*` and `[i`.
=> Make hop.hint_word depend on iskeyword

doc/hop.txt, lua/hop/highlight.lua, lua/hop/hint.lua, lua/hop/init.lua, lua/hop/priority.lua
The first commit is a general refactoring of the grey/hints highlighting to use the priority key when creating an extmark. An advantage of this method is that you don't have to grey everything out every time the hints are refined. This is similar to #62 except I went further with the refactoring and also explained how the priority key works by looking at neovims source code. This commit also made it easier to add the next commit.
The second commit adds a "virtual cursor" when hopping by putting virtual text of a unicode block character where the cursor was located before hopping. This makes it easy to see where the cursor was when you started the hop.
One caveat of this is that it blocks the character underneath the virtual cursor however this should be fine as the user won't need to hop …
=> Add highlighting to show where the cursor was before a hop

lua/hop/init.lua
Small follow up PR to #68. On neovim 0.5.1, #68 greys out lsp diagnostics virtual text however recent changes on nightly seem to make this no longer happen. The diagnostics don't become grey even though hop uses a very high priority for the grey highlight.
Luckily on nightly there are new functions for hiding and showing diagnostics which solve this problem. This PR checks whether the user is on nightly and if they are hides the diagnostics whilst hopping.
=> fix: diagnostics not greyed out on neovim nightly

lua/hop/jump_target.lua
When the first character of a pattern is a space, we assume the pattern
is not case-sensitive.
Fixes #74.
=> Fix broken case-sensitivy with spaces.

doc/hop.txt, lua/hop/init.lua, lua/hop/jump_target.lua, lua/hop/window.lua
This was introduced in #205. The way window contexts are passed around
was altered (the get_window_context() function doesn’t return the
context immediately but now returns every contexts right away, unless a
flag is passed — multi_windows = false or nil).
Also, I realized why fixing that bug that opts.multi_windows and
opts.current_line_only are unsound used together. I don’t block the
behavior (yet? it’s weird) but I notify the user not to do that.
Fixes #214. Relates and probably fixes #213 as well.
=> Fix current_line_only bug.

plugin/hop.vim
lua is not available in nvim below v0.5.0.
=> Fix neovim version

doc/hop.txt
👋 Hey, when building `hop.nvim` I ran into an error:
```
E154: Duplicate tag "hop.hint_words" in file ./doc/hop.txtFailed to build help tags!
```
Looks like there was a typo with `hop.hint_words` and it should be `hop.hint_anywhere` to avoid the duplicatation.
=> doc: duplicate `hint_words` should be `hint_anywhere`

README.md, doc/hop.txt, lua/hop/defaults.lua, lua/hop/hint.lua, lua/hop/jump_target.lua
For example, now you can use this command to hint word endings:
```lua
:lua require"hop".hint_words({hint_position = require"hop.hint".HintPosition.END})
```
Found discussion near this feature in this thread https://github.com/phaazon/hop.nvim/issues/71#issuecomment-1016617327
=> Added new option to select hint position in match.

lua/hop/jump_target.lua, lua/hop/window.lua
Skip foldline's targets to avoid unneccessary regex match like the pictures showing below.
***Without this commit:***
***With this commit***
(This commint is also important for the `match-mappings` feature of #133, which can avoid searching cost for regex match on large mappings)
=> fix: skip foldline's targets

lua/hop/init.lua
Pressing CTRL-C was not properly aborting :HopPattern, because it still
returned some pattern from the function. Make it equivalent to CR.
=> fix: make ctrl-c equivalent to esc in :HopPattern prompt

lua/hop/init.lua
Support `<NL>` (`<C-J>`) as an alternative to `<CR>`, and `<C-H>` as an alternative to `<BS>`.
=> feat: <NL> and <C-H> support in :HopPattern prompt

lua/hop/init.lua, lua/hop/window.lua
getcurpos()'s curswant refers to the _preferred_ column, and it
signifies to what column the cursor should get back to after moving over
empty or shorter lines. It does not refer to the actual cursor position,
and cannot be used here because it can report a column that does not
actually exist on the current line.
virtcol() would be more correct, as it reports the actual column.
However, it counts hard tabs as their screen width, could still cause
out of range errors.
Instead get the current line up to the cursor and calculate the column
with strwidth().
Fixes #261 #267
=> fix: fix "col value outside range" error

lua/hop/init.lua
I think this is the desired behavior for any pending operation destination
Jumping backwards seems to already works fine (it leaves out the character you jump from but that is already how vim works)
Jumping forwards needs to be incremented if done from a pending operation context
=> fix: pending operation col increment

lua/hop/perm.lua
Closes #263.
(Sorry for the mess in the linked issue. I didn't know GitHub notifies all pushes like this. It won't happen again.)
=> Fix broken matching when magic chars are included in opts.keys.

lua/hop/init.lua
This PR allows motion with `count`.
e.g. When using [keybindings], pressing `d2f"` will delete chars up to 2nd `"` (just like a vim motion).
[keybindings]: https://github.com/phaazon/hop.nvim#keybindings
=> Support `count`-ed motion

lua/hop/init.lua, lua/hop/window.lua
This PR fixes these incorrect behavior.
---
`:HopChar1AC` with `a` shows a hint on the 1st char:
```
ああ*あaaa
```
---
`:lua require'hop'.hint_char1 { direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, hint_offset = -1 }` with `a` and select 1st `a` raises the error `Column value outside range`:
```
aaaあ*ああ
```
=> Fix incorrect behavior in multi-byte chars

lua/hop/hint.lua, lua/hop/jump_target.lua
This commit has the disavantage of preventing people from jumping to empty lines if they have shifted their view. However, I think it’s okay because we cannot place a hint in a buffer that is not visible, unless we start hacking around with the text_column thing, and I don’t think it’s worth it for now.
Fixes #292.
=> Fix column out of range for HopLine*.

lua/hop/init.lua
Some buffers will be unloaded, and we need to check that when quitting. That commit fixes that issue, which is not strictly #278 but very similar.
We might not something else to completely fix their problem but that was a bug for sure hiding in the shadows.
=> Fix quitting in MW when a float is present.

lua/hop/health.lua
From the help:
```
- *health#report_error* *vim.health.report_error()*     Use |vim.health.error()| instead.
- *health#report_info* *vim.health.report_info()*       Use |vim.health.info()| instead.
- *health#report_ok* *vim.health.report_ok()*           Use |vim.health.ok()| instead.
- *health#report_start* *vim.health.report_start()*     Use |vim.health.start()| instead.
- *health#report_warn* *vim.health.report_warn()*       Use |vim.health.warn()| instead.
```
=> health: Update from deprecated health api
