phaazon/hop.nvim

README.md, doc/hop.txt, lua/hop/init.lua
=> Update documentation regarding setting up.

lua/hop/init.lua
=> Fix hint_patterns() by denying using empty patterns.

lua/hop/init.lua
=> Fix the last line not being cleared after Hop exits in some situations.

lua/hop/init.lua
Now Neovim head has `nvim_echo()` to show command messages with highlighting.
NOTE: It cannot deal with the `teasing` option from `refine_hints()`.
=> Use nvim_echo() instead of calling echohl

lua/hop/hint.lua, lua/hop/init.lua, lua/hop/perm.lua
Unicode keys can now be used completely. The initial algorithm wasn’t
tested though and is going to be ruled out entirely soon, so no need to
fix it — and it’s weaker anyway.
Relates to #73. Might relate to #72 but do not expect this commit to fix
it, though.
=> Fix unicode key set.

lua/hop/hint.lua
=> Fix column computation for empty lines.

lua/hop/init.lua
=> Revert "Switch off hack to mitigate neovim extmark bug."

lua/hop/init.lua
Quick fix, perhaps an oversight :)
=> fix: 'pat' and 'ok' were uneccesary globals

lua/hop/init.lua
=> Update the jump list on a sole occurrence.

lua/hop/init.lua
Reverts phaazon/hop.nvim#157
Fixes #178
=> Revert "fix: diagnostics not greyed out on neovim nightly"

lua/hop/init.lua
Reverts phaazon/hop.nvim#179
The joy of reverting reverts.
=> Revert "Revert "fix: diagnostics not greyed out on neovim nightly""

doc/hop.txt, lua/hop/init.lua
=> Implement callback support for hint reducing.

doc/hop.txt, lua/hop/defaults.lua, lua/hop/hint.lua, lua/hop/init.lua
=> Add (displayed) uppercase label support.

README.md, doc/hop.txt, lua/hop/init.lua
=> Support falling back to 1-char from 2-char mode.

README.md, doc/hop.txt, lua/hop/health.lua
=> Add :checkhealth support.

README.md, doc/hop.txt, lua/hop/defaults.lua, lua/hop/init.lua, lua/hop/jump_target.lua, lua/hop/window.lua, plugin/hop.vim
Add `multi_windows` support following #133.
=> Add multi_windows support

doc/hop.txt, lua/hop/init.lua, lua/hop/jump_target.lua, plugin/hop.vim
=> Add new HopAnywhere commands

lua/hop/window.lua
=> Unicode cursor location fix

doc/hop.txt, lua/hop/highlight.lua, lua/hop/hint.lua, lua/hop/init.lua, lua/hop/jump_target.lua
An example for previewing HopPattern:
=> Add support for previewing HopPattern

README.md
Addresses the issue mentioned in #285
=> More readable keybinding from lua example. #285

lua/hop/init.lua
=> expose get_input_pattern to be called externally

lua/hop/init.lua
This small fix does what it says on the tin: 
- `create_hint_state` now saves the users state of the `cursorline` option
- `add_virt_cur` disables cursorline if true
- if `cursorline` is true, disable it temporarily in `add_virt_cur`, restore users cursorline state from `hint_state` in `quit`
The reason I made this fix was because the highlighting in Hop looks slightly strange if you have `cursorline` highlighting set to be a solid background color (instead of the default underline), see attached image below
I've done some testing on my end for this small fix, but might be worth someone else having a look as well :)
EDIT: uploaded clearer screenshot of issue
=> added a cursorline flag and automatic toggling when entering/exiting hop

doc/hop.txt, lua/hop/init.lua, lua/hop/jump_target.lua
Extract them once instead of compiling them for every visual lines.
=> Cleanup some regexes.
